[package]
name = "QuickChemDraw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.14"
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
